import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

// Source-level, like the other metadata assertions: the route is a Worker handler and rendering it
// needs the whole build, but what matters here is which agents are named and that the wildcard rule
// still lets search in.
const route = await readFile(new URL("../app/robots.txt/route.ts", import.meta.url), "utf8");

test("training crawlers are named and disallowed", () => {
  // The list is the file's own, not Cloudflare's dashboard toggle -- robots.txt is generated by this
  // route, so letting Cloudflare manage it too would put two systems in charge of one response.
  for (const agent of ["GPTBot", "ClaudeBot", "Google-Extended", "Applebot-Extended", "CCBot"]) {
    assert.match(route, new RegExp(`"${agent}"`), `${agent} should be in TRAINING_CRAWLERS`);
  }
  assert.match(route, /TRAINING_CRAWLERS\.flatMap[\s\S]{0,120}Disallow: \/"/);
});

test("search and agents are still welcome", () => {
  // Blocking training must not block the bots that send people here, or the ones that cite the site
  // in an answer. Only /api/ is closed, because each of those is an uncached D1 query with nothing
  // to index.
  assert.match(route, /"User-agent: \*",\s*\n\s*"Allow: \/"/);
  assert.match(route, /"Disallow: \/api\/"/);
  assert.doesNotMatch(route, /"Disallow: \/",\s*\n\s*`Sitemap/);
});

test("the sitemap is advertised from the request origin", () => {
  // Not a build-time constant: the same worker answers on workers.dev and on aboard.cc, and a
  // hardcoded origin would point one of them at the other.
  assert.match(route, /new URL\(request\.url\)\.origin/);
  assert.match(route, /Sitemap: \$\{origin\}\/sitemap\.xml/);
});
