// A route handler rather than a file in public/, so the sitemap it advertises is absolute and
// correct on whatever origin the worker is actually serving -- the workers.dev subdomain today, a
// custom domain later -- without a build-time constant that would quietly go stale.

// Crawlers that collect pages to TRAIN models, as distinct from the two kinds this file welcomes:
// search bots (which send people here) and answer agents (which cite the site in a reply, and are
// distribution rather than extraction).
//
// Written here rather than switched on in Cloudflare's dashboard, and that is the point. Cloudflare
// offers to manage robots.txt for you -- but this file is GENERATED by a Worker route, so accepting
// that offer puts two systems in charge of one response. Whichever wins, the answer stops living in
// version control and stops being covered by a test. One owner, and it is this file.
//
// robots.txt is a request, not a fence: the note under Cloudflare's own toggle says the same thing.
// Anything that ignores it needs a WAF rule, which is where Cloudflare's Search/Agent/Training
// controls actually earn their keep.
//
// CCBot is deliberately on this list AND worth a second thought. It is Common Crawl -- the same
// index this project reads to discover new ATS boards. Blocking it does not affect our ability to
// read CC; it only keeps this site out of future crawls, which also keeps it out of anything built
// on top of them. That is a trade, not a free win: less reach, less exposure to whoever builds the
// next aggregator from the same source.
const TRAINING_CRAWLERS = [
  "GPTBot",
  "ClaudeBot",
  "anthropic-ai",
  "Google-Extended",
  "Applebot-Extended",
  "meta-externalagent",
  "FacebookBot",
  "Bytespider",
  "cohere-ai",
  "Diffbot",
  "Omgilibot",
  "CCBot",
];

export const dynamic = "force-dynamic";

export function GET(request: Request) {
  const origin = new URL(request.url).origin;
  const body = [
    ...TRAINING_CRAWLERS.flatMap((agent) => [`User-agent: ${agent}`, "Disallow: /", ""]),
    "User-agent: *",
    "Allow: /",
    // The JSON endpoints answer the same rows the page already renders, and each one is an
    // uncached D1 query. There is nothing to index and every crawl of them is billed.
    "Disallow: /api/",
    "",
    `Sitemap: ${origin}/sitemap.xml`,
    "",
  ].join("\n");

  return new Response(body, {
    headers: {
      "content-type": "text/plain; charset=utf-8",
      "cache-control": "public, max-age=3600",
    },
  });
}
